language: node_js
node_js:
  - "node"
  
sudo: required

services:
  - docker
  
before_install:
  - docker pull neo4j:latest
  - docker run -d -p 127.0.0.1:7687:7687 neo4j:latest 
  - npm i -g mocha
  
cache:
 directories:
   - "node_modules"