language: node_js
node_js:
  - "node"
  
sudo: required

services:
  - docker
  
before_install:
  - docker run -d --publish=127.0.0.1:7687:7687 --env NEO4J_AUTH=neo4j/graphtastic neo4j:latest 
  
cache:
 directories:
   - "node_modules"